

dependencies {

    implementation(libs.anvillib.registrum)
    implementation(libs.anvillib.network)
    implementation(libs.anvillib.rendering)

    jarJar(libs.anvillib.registrum)
    jarJar(libs.anvillib.network)
    jarJar(libs.anvillib.rendering)

//    implementation(libs.animata4j.core)
//    jarJar(libs.animata4j.core)

}