

dependencies {
//    api "maven.modrinth:simpleanimator:$simpleanimator_maven_version"

    implementation group: 'dev.anvilcraft.lib', name: 'anvillib-registrum-neoforge-26.1', version: anvillib_version
    implementation group: 'dev.anvilcraft.lib', name: 'anvillib-network-neoforge-26.1', version: anvillib_version
    implementation group: 'dev.anvilcraft.lib', name: 'anvillib-rendering-neoforge-26.1', version: anvillib_version

    jarJar group: 'dev.anvilcraft.lib', name: 'anvillib-registrum-neoforge-26.1', version: anvillib_version
    jarJar group: 'dev.anvilcraft.lib', name: 'anvillib-network-neoforge-26.1', version: anvillib_version
    jarJar group: 'dev.anvilcraft.lib', name: 'anvillib-rendering-neoforge-26.1', version: anvillib_version

//    runtimeOnly "maven.modrinth:sodium:$sodium_maven_version"
//    runtimeOnly "maven.modrinth:iris:$iris_maven_version"

//    api "maven.modrinth:sodium:$sodium_maven_version"
//    api "maven.modrinth:iris:$iris_maven_version"
//    api "maven.modrinth:embeddium:$embeddium_maven_version"
}